### ISSUE TITLE
Demo for OSX

### ISSUE THREAD

**Issue by Chuongv** [dvor/objcTox#146] opened 2015-12-12 02:31 UTC
A demo for OSX is needed. This also provide us a a way to test audio and video later on

**Comment by dvor** [comment] 2015-12-12 11:39
I think it is a duplicate of https://github.com/Antidote-for-Tox/objcTox/issues/118

**Closed as completed by dvor** 2015-12-12 11:39 UTC
Labels: enhancement

**Comment by Chuongv** [comment] 2015-12-12 15:33
Ah whoops! Thanks
